### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode characters in position 5-10: character maps to <undefined>

### ISSUE THREAD

**Issue by ultra-taco** [SHUR1K-N/RARNinja-RAR-Password-Cracking-Utility#1]
```
$ pip install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: rarfile in c:\users\alex\appdata\roaming\python\python39\site-packages (from -r requirements.txt (line 1)) (4.0)
Requirement already satisfied: colorama in c:\users\alex\appdata\roaming\python\python39\site-packages (from -r requirements.txt (line 2)) (0.4.4)
Requirement already satisfied: termcolor in c:\users\alex\appdata\roaming\python\python39\site-packages (from -r requirements.txt (line 3)) (1.1.0)

$ python RARNinja.py
Traceback (most recent call last):
  File "C:\Users\Alex\TempGitProjects\RARNinja-RAR-Password-Cracking-Utility\RARNinja.py", line 78, in <module>
    printBanner()
  File "C:\Users\Alex\TempGitProjects\RARNinja-RAR-Password-Cracking-Utility\RARNinja.py", line 27, in printBanner
    print(BANNER1), print(BANNER2), print(BANNER3), print(BANNER4)
  File "C:\Users\Alex\AppData\Roaming\Python\Python39\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\Alex\AppData\Roaming\Python\Python39\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\Alex\AppData\Roaming\Python\Python39\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\Alex\AppData\Roaming\Python\Python39\site-packages\colorama\ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
  File "C:\Program Files\Python3.9\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 5-10: character maps to <undefined>
```

**Comment by SHUR1K-N** [comment]
Since you're running a Unix system, you may try the following to see if any one of them works:

`python2 RARNinja.py`
`python3 RARNinja.py`
